### ISSUE TITLE
docker中运行ready之后立即调bot.Contact.findAll() 获取不到完整的联系人列表

### ISSUE THREAD

**Issue by atorber** [padlocal/wechaty-puppet-padlocal#106]
在docker中运行ready之后立即调bot.Contact.findAll() 获取不到完整的联系人列表，只能拿到当前登陆账号自己的信息

- 本地pc运行和服务器直接运行不会有这个问题
- 相同的代码使用wechaty-puppet-service客户端也不会有这个问题

```    
    .on("ready", async () => {
            let contactList = await bot.Contact.findAll()
            console.debug(contactList)
        })
```

**Comment by vinceyyy** [comment]
@atorber 想请问一下这个问题你解决了吗？我也遇到了很类似的问题。

**Comment by atorber** [comment]
需要padlocal在服务端操作一下，只有第一次登录可以算量获得联系人，之后登录是增量，频繁bot.Contact.findAll()可能出发微信风控，不建议每次ready都全量请求，需要本地或数据库缓存
之前咨询了官方的总结

**Comment by vinceyyy** [comment]
> 需要padlocal在服务端操作一下，只有第一次登录可以算量获得联系人，之后登录是增量，频繁bot.Contact.findAll()可能出发微信风控，不建议每次ready都全量请求，需要本地或数据库缓存
> 之前咨询了官方的总结

谢谢回答。是需要联系padlocal的客服来操作吗？
我遇到的情况是直接npm运行代码没有任何问题，build成docker镜像就会这样，在所有的服务器上都是一样的问题。不知道padlocal是怎么判断第一次登陆和之后登陆的。

**Comment by vinceyyy** [comment]
经过作者回复已经解决了问题🙏

解决方法是在调用`Wechaty.Contact.findAll()`之前先调用`wechaty-puppet-padlocal.syncContact()`，等同步结束后就可以正常获取联系人了

**Comment by huan** [comment]
It seems that the `ready` event should not emit until the `syncContact()` has been returned.

**Comment by chenbb0128** [comment]
> 经过作者回复已经解决了问题🙏
> 
> 解决方法是在调用`Wechaty.Contact.findAll()`之前先调用`wechaty-puppet-padlocal.syncContact()`，等同步结束后就可以正常获取联系人了

请问一下，wechaty-puppet-padlocal.syncContact() 应该如何使用，希望得到回复

**Comment by atorber** [comment]
> wechaty-puppet-padlocal.syncContact()

@huan I wonder if we can automatically call wechaty-puppet-padlocal.syncContact() in onScan event when it is called in puppet-padlocal？

**Comment by huan** [comment]
Wechaty should not know anything from the PadLocal except the Puppet Interface.

This logic should belong to the PadLocal and deal I side it.

**Comment by atorber** [comment]
Yes, I mean to implement the above operations in the onScan event of puppet-padlocal， @padlocal do you think this is reasonable？
