### ISSUE TITLE
Can we have more details about how to run it

### ISSUE THREAD

**Issue by treeguard** [padlocal/wechaty-puppet-padlocal#2]
I am very interested in how to run it, can you describe a little bit about how to use this puppet?

**Comment by padlocal** [comment]
Hey man, we are still preparing for the initial launch, will reach beta test very very soon. 
Detailed instructions will show you how to use this puppet then.
Thanks for your patience.

**Comment by padlocal** [comment]
Hi
https://github.com/padlocal/wechaty-puppet-padlocal

**Comment by padlocal** [comment]
Hi @treeguard ,
README is updated, more information is provided for you to use padlocal
