### ISSUE TITLE
Install OSS.Chat for issue notification in WeChat rooms

### ISSUE THREAD

**Issue by huan** [padlocal/wechaty-puppet-padlocal#51]
As our Wechaty developers' room will receive issues & comments from the community repos, I'd like to add `wechaty-puppet-padlocal` so that we can receive issues in this repo too.

Would you like to support this community feature? If you would like to, please install OSS.Chat GitHub Apps from <https://github.com/apps/osschat> to this repo, then I'll be able to set it up through <https://github.com/kaiyuanshe/osschat/blob/master/src/projects/wechaty.ts>.

**Comment by padlocal** [comment]
No problem, working on this

**Comment by huan** [comment]
Got it, and the oss.chat has been updated. New issues & comments from this repo will be sent to our Wechaty Puppet Service WeChat room from now.
