### ISSUE TITLE
message.from() is null

### ISSUE THREAD

**Issue by fangmuke** [padlocal/wechaty-puppet-padlocal#6]
![image](https://user-images.githubusercontent.com/26641510/99140522-a40cc580-267d-11eb-9b7b-8088d3a30322.png)
![image](https://user-images.githubusercontent.com/26641510/99140540-ba1a8600-267d-11eb-8352-1fe1d7b04656.png)

message.from() 是null，但在消息前却携带了form wxid

**Comment by padlocal** [comment]
Fixed by https://github.com/padlocal/wechaty-puppet-padlocal/commit/3aba53b70051db1b8d7ca9f61be0b4b59008920e, and published in version 0.1.5
