### ISSUE TITLE
无法获取群的二维码

### ISSUE THREAD

**Issue by xuwancheng** [padlocal/wechaty-puppet-padlocal#61]
取法获取群的二维码，代码如下：
const dingRoom = await this.Room.find({ topic: /^互动群/i })
    if (dingRoom) {
        var qrcode = await dingRoom.qrcode();
    }

报错如下：
(node:22996) UnhandledPromiseRejectionWarning: TypeError: dingRoom.qrcode is not a function
    at Wechaty.onMessage (e:\P-WeRobot\SourceCode_FindQR\index.js:63:37)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
<node_internals>/internal/process/warning.js:41
(node:22996) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
<node_internals>/internal/process/warning.js:41
(node:22996) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by padlocal** [comment]
Please stay signed on for at least 24 hours, then try again.
