### ISSUE TITLE
Unknown消息没有fromId, message.talker() 抛出错误

### ISSUE THREAD

**Issue by fangmuke** [padlocal/wechaty-puppet-padlocal#62]
![image](https://user-images.githubusercontent.com/26641510/113470721-480ad800-948a-11eb-88bd-0f2de759998c.png)
https://github.com/wechaty/wechaty/blob/5593742521f09422d24633ef07e150f15cc1298b/src/user/message.ts#L254
https://github.com/wechaty/wechaty/blob/5593742521f09422d24633ef07e150f15cc1298b/src/user/message.ts#L206
@huan

**Comment by huan** [comment]
A message with `unknown` type will give unexpected behavior, because it's unknown...

PR is welcome.

**Comment by padlocal** [comment]
PadLocal has supported pad message now
