### ISSUE TITLE
login failed: VError: request has been cancelled

### ISSUE THREAD

**Issue by suntong** [padlocal/wechaty-puppet-padlocal#66]
_Originally posted by @su27k-2003 in https://github.com/padlocal/wechaty-puppet-padlocal/issues/60#issuecomment-817784831_

> confirmed that the PadLocal Token Gateway is working without error now. But my wechaty python script (bot) generated the error below and the bot cannot send messages out anymore.
> As I didn't change the python script and the python script worked properly before we had the PadLocal Token Gateway issue#60, I suspect the change made for issue#60 caused the wechaty python error? Please let me know if you have any idea from the error message. Thanks. Happy to raise the issue with the wechaty python project if you think it's unrelated to the wechaty-puppet-padlocal.
> 
> 2021-04-12 22:31:04,394 - Wechaty - ERROR - internal error <(<Status.INTERNAL: 13>, '[tid:2bf0d6f4] request has been cancelled for reason: CLIENT_ERROR: [tid:2bf0d6f4] Exception while handling wechat request: [tid:2bf0d6f4] Fail to request short link for path:/mmtls/fff12b0e, data: 19f10300a10000009d0103f10100a8dc871d72a6c169757d25be45170dd83c99fe4a4b7cdecd8d7a078919a3b7ed7360743d7c0000006f010000006a000f01000000630100093a8000000000003d000c760485b1f9cfbb94ab284ae700481cef2f3f5e5e354ec0a86f2c47fb26174683d940f75a1dc72775b21b627626f5f445374549c0fe9a704b147cd7b151c7433b746942c2df843bb9a440f533ed5dfeeeeae983ed2bc719f1030024b205b223ffdd198f0c284ceb01138f66d538d9fc4fa049f2544a405c6689f4332b3a636517f10300cdda29519dcd8d5833a379c67ebf941ace61627d361a9f4496274549226d52c51d1b3dedde00d8d21761f111fa87a89c17acbf2221252cf54e0831389a08ec26c025a5e4e0fee5729ccf09cb34f3537dab8d87a3428b2cd6b8989af0f7a96c537eac3da52ecb404b849cf1f7a3b6558ff3e9d3b5d083fdf1eb08427b4e86786c80d5df6e006645697b47688b5102260f1ec2c26e81ec869d7d78447c10b8bd09bf9cee50ccb3b2df1573cedc472d1fba18c255af2db3da7e3a0a7b5ea5e6fcfdfd61715bb2cb3dccca9b4ff5416915f10300171159eae3e7fc224bd83daca00bccabe0198147ee2ac520, after max retry:5: ENOTFOUND: getaddrinfo ENOTFOUND sgextshort.wechat.com', None)>

**Comment by suntong** [comment]
The login problem is fixed, but login won't stay steady. Will get into problem exactly as what @su27k-2003 reported above.

Thus close the previous one and  open this one.

<details>
<summary>
More Info/Details
</summary>

```shell
       - wechaty-puppet-padlocal version: 0.2.37
       - padlocal-ts-client version: 0.2.26

22:21:29 INFO TestBot onScan: Scanned(3)
22:21:35 INFO TestBot onScan: Confirmed(4)
22:21:42 INFO TestBot Contact<xxx> login

22:23:01 ERR [PuppetPadlocal] login failed: VError: [tid:28e6772f] request has been cancelled for reason: CLIENT_ERROR: [tid:28e6772f] Exception while handling wechat request: [tid:28e6772f] Fail to request short link for path:/mmtls/fff1edfe, data: 19f10300a10000009d0103f10100a813fe851bcb5356360f11ec253af3ae4e0bcc0f8c7f1f5840135dd933372be7786075006c0000006f010000006a000f01000000630100093a8000000000003d000c576fa72f87d539ea2063306a00482d15cc0a02b954924b9a12aa71c1b16202f287ec55206bbbac336334d3f584972603b8dea9b6c25de60203ba8877c6ebc9292869df5aa6bec0a44194e0cc12c44f1917222154346319f10300245b54cfe2562a66898ae2f8178eb50d0fdf8e9d3ca7e0d0228279b6b793fcb6a494c4117817f10300cdbafc19dbf5c9114d4724113f922fc3911ad53755c569b6921e0d302391fbf6d7dc2abc5ae0309131bf239bbb6cd3f2c29e68b04670ab5147e2843309260a76a5bac77b434f504fdfbd83321054c83d7bbf6ad1bcb2fb6b07e5e54528e4aa089d99cdf89d2af366425a1f6464a53b07a1b178eedb805330fe24eabb7e1e136c09db7ca2a9880872faaacc143261f3d91c4935ae2e2586395bee6b4ea60a31edca9dde6189ff1b2c3ee2a8139a5618199f7a562c2c9fcf5623875fdbe0f6193693ecbfd44cc0d0438a1c836c14fa15f10300174540574c6a93c38a86ba4b7b12c9e6da16e880ef25693f, after max retry:5: ENOTFOUND: getaddrinfo ENOTFOUND sgextshort.wechat.com
    at Request._failAllPendingRequest (/path/to/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at Request.error (/path/to/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:347:10)
    at Request.<anonymous> (/path/to/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/path/to/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/dist/Request.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:143) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hasContact' of undefined
    at PuppetPadlocal._getRoomMemberList (/path/to/wechaty-puppet-padlocal-demo/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1311:50)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at PuppetPadlocal.roomMemberList (/path/to/wechaty-puppet-padlocal-demo/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1159:27)

22:23:03 INFO [PuppetPadlocal] start login with type: AutoLogin
22:23:05 INFO TestBot Contact<xxx> login
22:23:18 ERR [PuppetPadlocal] login failed: VError: [tid:8ec58ed4] request has been cancelled for reason: CLIENT_ERROR: [tid:8ec58ed4] Exception while handling wechat request: [tid:8ec58ed4] Fail to request short link for path:/mmtls/fff1ee1c, 

. . . repeating every few minutes . . .
```

</details>

**Comment by padlocal** [comment]
Fixed

**Comment by suntong** [comment]
OK, thx, I'll try tonight.

@su27k-2003, would you try as well pls?

**Comment by su27k-2003** [comment]
Thanks, @suntong happy to test it
My token is expired so I need to ask @padlocal to extend my tokan for the testing first

**Comment by suntong** [comment]
I checked and can confirm that it is working fine for me now. 

Thanks a lot for you and your team's hard work @padlocal !

**Comment by padlocal** [comment]
Happy to know that it's working for you guys now.

**Comment by su27k-2003** [comment]
@padlocal I've tested it but confirmed my PadLocal Token Gateway stopped with errors below.
I'll create a new issue since I believe I'm facing a different issue here. Thanks.

Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! wechaty@0.56.6 io-client: `ts-node bin/io-client`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the wechaty@0.56.6 io-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /bot/.npm/_logs/2021-04-25T14_17_42_806Z-debug.log

**Comment by suntong** [comment]
`bin/io-client`? Have you tried the official demo from
https://github.com/padlocal/wechaty-puppet-padlocal-demo?

Maybe it's time I contribute my demo code there.
@padlocal, would you accept my PR to put my demo code there?
