### ISSUE TITLE
[Help]二维码无法登陆

### ISSUE THREAD

**Issue by magus0219** [padlocal/wechaty-puppet-padlocal#79]
@padlocal @huan 

大佬好，使用测试token，手机扫描二维码之后，继续弹出新二维码，日志如下：

```
19:02:25 INFO TifaBot onScan: Waiting(2)

 ▼▼▼ Please scan following qr code to login ▼▼▼

*QRCODE here*

19:02:41 INFO TifaBot onScan: Confirmed(4)
19:02:42 VERB StateSwitch <PuppetPadlocal> off(pending) <- (false)
19:02:42 VERB StateSwitch <PuppetPadlocal> off(true) <- (pending)
19:02:43 VERB StateSwitch <PuppetPadlocal> on(pending) <- (false)
19:02:44 INFO [PuppetPadlocal] start login with type: QrLogin
19:02:44 INFO TifaBot onScan: Waiting(2)

 ▼▼▼ Please scan following qr code to login ▼▼▼

*QRCODE here*

```

求助，谢谢。

**Comment by magus0219** [comment]
尝试登陆demo项目，问题一样存在。

**Comment by metanoia1989** [comment]
也遇到一样的问题，扫码之后依旧显示二维码

**Comment by chenhua19940128** [comment]
也遇到一样的问题，扫码之后依旧显示二维码

**Comment by Terencesun** [comment]
也遇到一样的问题，扫码之后依旧显示二维码（不是跟队形，是真的遇到这个问题_(:з」∠)_）

**Comment by padlocal** [comment]
各位，因为最近微信刚刚更新了规则，限制了某些账号的登录。我们也正在努力修复，有进展会另行通知。

**Comment by hiabrazame** [comment]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/11461296/119262498-10a8e400-bc0e-11eb-9f9d-54022854c029.png">
@padlocal 请问这个是同一个错误吗？我扫码后显示bad request error

**Comment by sdwhwzp** [comment]
今天刚购买了padlocal 但是出现了 二维码无法登录，不知道什么时候能修复好

**Comment by frankgo81** [comment]
我也出现了这个问题。无法登陆。

**Comment by padlocal** [comment]
Hi All，this issue has been fixed. If you have any further issues, pls reopen and follow up this thread.

**Comment by treeguard** [comment]
I still have the issue now, do I need to update padlocal version?

**Comment by padlocal** [comment]
@treeguard Add our technical support wechat: "padlocal", help you to solve the issues.
